In [1]:
import numpy as np

In [2]:
my_arr = np.arange(100)


In [4]:
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
data = np.random.randn(2, 3)
data

array([[ 0.62960636, -0.97237919, -1.05949322],
       [-0.87507768,  1.34643008, -0.95846131]])

In [7]:
data * 10


array([[  6.29606359,  -9.72379187, -10.59493221],
       [ -8.7507768 ,  13.4643008 ,  -9.58461311]])

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [10]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
np.empty((3, 2))


array([[ 6.29606359,  9.72379187],
       [10.59493221,  8.7507768 ],
       [13.4643008 ,  9.58461311]])

In [15]:
a = np.empty((4, 3, 2))

In [17]:
np.ones_like(a)

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [22]:
np.full_like(a,4)

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [23]:
arr = np.arange(10)

In [24]:
arr[5]


5

In [25]:
arr[5:8]


array([5, 6, 7])

In [34]:
arr[:]
arr[6:-1]
arr[-4]


6

In [35]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [40]:
arr2d[1][1]

5

In [45]:
arr2d.shape

(3, 3)

In [46]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


In [47]:
arr3d.shape

(2, 2, 3)

In [48]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [49]:
arr3d[1][1][1]

11

In [58]:
arr2d[:2, 1:]


array([[2, 3],
       [5, 6]])

In [59]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

1st one is for dimensions
2nd one is for rows
3rd one is for columns

In [77]:
arr3d[:2, :1,2:]   
                

array([[[3]],

       [[9]]])

In [82]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [80]:
data = np.random.randn(7, 4)
data

array([[ 0.18439267, -1.8822802 ,  0.18168331, -2.06914124],
       [-1.71592627, -0.51536741, -1.11589986, -1.04993183],
       [ 0.1052842 , -0.29164946, -0.16155416,  0.35480806],
       [ 0.69225226,  0.24232798, -0.6220308 , -0.55674319],
       [ 1.27725463,  1.76539849, -1.61972204,  2.35890623],
       [ 1.26177311, -0.70357751,  1.00022516,  0.96868865],
       [ 2.75618347,  0.96774958,  0.3480992 , -0.16957236]])

In [81]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [83]:
data[names == 'Bob']


array([[ 0.18439267, -1.8822802 ,  0.18168331, -2.06914124],
       [ 0.69225226,  0.24232798, -0.6220308 , -0.55674319]])

In [85]:
data[names == 'Bob', 3]


array([-2.06914124, -0.55674319])

In [86]:
data[~(names == 'Bob')]


array([[-1.71592627, -0.51536741, -1.11589986, -1.04993183],
       [ 0.1052842 , -0.29164946, -0.16155416,  0.35480806],
       [ 1.27725463,  1.76539849, -1.61972204,  2.35890623],
       [ 1.26177311, -0.70357751,  1.00022516,  0.96868865],
       [ 2.75618347,  0.96774958,  0.3480992 , -0.16957236]])

In [87]:
data[data < 0] = 0


In [88]:
data

array([[0.18439267, 0.        , 0.18168331, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.1052842 , 0.        , 0.        , 0.35480806],
       [0.69225226, 0.24232798, 0.        , 0.        ],
       [1.27725463, 1.76539849, 0.        , 2.35890623],
       [1.26177311, 0.        , 1.00022516, 0.96868865],
       [2.75618347, 0.96774958, 0.3480992 , 0.        ]])

In [89]:
for i in range(2,8):
    print(i)

2
3
4
5
6
7


In [101]:
arr = np.arange(32).reshape((4,8))

In [102]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [104]:
d = arr.T

In [105]:
np.dot(d, arr)

array([[ 896,  944,  992, 1040, 1088, 1136, 1184, 1232],
       [ 944,  996, 1048, 1100, 1152, 1204, 1256, 1308],
       [ 992, 1048, 1104, 1160, 1216, 1272, 1328, 1384],
       [1040, 1100, 1160, 1220, 1280, 1340, 1400, 1460],
       [1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536],
       [1136, 1204, 1272, 1340, 1408, 1476, 1544, 1612],
       [1184, 1256, 1328, 1400, 1472, 1544, 1616, 1688],
       [1232, 1308, 1384, 1460, 1536, 1612, 1688, 1764]])

In [110]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [130]:
arr.transpose((1, 0, 2))


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [118]:
arr.transpose(0, 2, 1)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [131]:
arr.transpose(0, 1, 2)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])